@startuml
skinparam linetype ortho
'title: Cash Register Controller Thread
skinparam monochrome true

start
repeat
if (Last Command) then (None)
    :Wait for Command;
    :Process new command;
else (not None)
    if (Wait for Command or Timeout) then (Command)
        :Process new Command;
    else (Timeout)
        :Process last Command;
    endif
endif
if (Command return value) then (True)
    :Last Command = None;
else (not True)
    :Last Command = Command;
endif
@enduml