@startuml
' title Cash Register Controller States
' skinparam linetype ortho

skinparam monochrome true


hide empty description

[*] -> DENYING_CASH

DENYING_CASH -> ACCEPTING_CASH: ACCEPT_CASH

ACCEPTING_CASH --> PAYMENT_READY: balance sufficient
ACCEPTING_CASH -left-> DENYING_CASH: DENY_CASH
ACCEPTING_CASH -> ACCEPTING_CASH: balance\ninsufficient

PAYMENT_READY -> DENYING_CASH: TAKE_MONEY\nor\nDENY_CASH

@enduml