@startuml
skinparam linetype ortho
left to right direction
skinparam nodesep 30
title: FerryTix Class Diagram
abstract class PaymentMethod

class FaehrCardPayment {
    + uuid: UUID
}
FaehrCardPayment .|> PaymentMethod
FaehrCardPayment -left-> FaehrCard

class CashPayment {
    + denominations: array<integer>
    + change: array<integer>
}

CashPayment .|> PaymentMethod

class ECCardPayment {

}

ECCardPayment .|> PaymentMethod

class BankTransferPayment {

}

BankTransferPayment .up|> PaymentMethod

class PayPalPayment {

}

PayPalPayment ..|> PaymentMethod

class Payment {
    + uuid: UUID
    + amount: integer
    + method: PaymentMethod
}

Payment --> PaymentMethod

class TicketSale {
    + uuid: UUID
    + issuedBy: UUID
    + issuedAt: DateTime
    + returnValid: boolean
    + from: MachineLocation
    + payment: Payment
    + positions: array<<Fare, integer>>
}

TicketSale-up-> VendingMachine
TicketSale-> MachineLocation
TicketSale -up> Fare
TicketSale -left-> Payment


class TicketClass {
    + bicycle: boolean
    + return: boolean
    + reduced: boolean
    + staff: boolean
}

class TopUp {
    + uuid: UUID
    + for: UUID
    + issuedAt: DateTime
    + issuedBy: UUID
    + amount: integer
    + paid: integer
    + payment: Payment
    + initial: boolean
}

TopUp-> FaehrCard
TopUp-> VendingMachine
TopUp--> Payment

class StaffMember {
    + uuid: UUID
    + firstName: string
    + lastName: string
    + role: StaffRole
}

StaffMember--> StaffRole

enum StaffRole {
    Admin
    Captain
    Cashier
    other
}

class FaehrCard {
    + uuid: UUID
    + ownedBy: Union<null, UUID>
    + balance: integer
    + issuedAt: DateTime
    + issuedBy: Union<null, UUID>
    + topUps: array<TopUp>
}

FaehrCard-> StaffMember
FaehrCard--> VendingMachine

class MachineConfiguration {
    + forMachine: UUID
    + maxBicycles: integer
    + maxBicyclesTolerance: integer
    + maxPassengers: integer
    + maxPassengersTolerance: integer
    + fares: array<Fare>
}

MachineConfiguration--> Fare

class Fare {
    + ticketClass: TicketClass
    + fare: integer
}

Fare-up> TicketClass

' enum MachineCommand {
'     setSignalRed
'     setSignalGreen
'     stopVending
'     startVending
' }

enum MachineLocation {
    Bislich
    Xanten
}

class VendingMachine {
    uuid: UUID
    location: MachineLocation
}

VendingMachine-> MachineLocation

class MachineStatus {
    vending: boolean
    waiting: array<WaitingPassenger>
}

MachineStatus--> WaitingPassenger

class WaitingPassenger {
    ticketClass: TicketClass
    waitingSince: DateTime
}

WaitingPassenger--> TicketClass

@enduml