@startuml
skinparam linetype ortho
title: Note Acceptor Register Thread
start
repeat :Release **Command Lock**;
:Wait for Edge;
:Acquire **Command Lock**;
backward :End of Bill;
    repeat :Sleep 125 ms;
    ':Release **Command Lock**;
    repeat while (Wait for Edge) is (    Edge\n    detected) not (\nTimed out)
@enduml