@startuml
skinparam linetype ortho
title: Note Acceptor Register Thread
start
repeat :Wait for Edge;
:Acquire **Command Lock**;
    repeat :Sleep 110 ms;
    ':Release **Command Lock**;
    repeat while (Wait for Edge) is (    Edge\n    detected) not (Timed out after 100 ms\n)
     :Write Bill to Message Queue;
    backward :Release **Command Lock**;
@enduml